[tool.black]
line-length = 120
target-version = ['py27']
include = '\.pyi?$'
exclude = '''
(
  /(
      \.eggs         # exclude a few common directories in the
    | \.git          # root of the project
    | \.tox
    | build
    | dist
  )/
)
'''
